//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopBrowser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 function clearCookie() {            
        ///            var keys = document.cookie.match(/[^ =;]+(?=\=)/g);
        ///            if (keys) {
        ///                for (var i = keys.length; i--;) {
        ///                	console.log(keys[i]);
        ///                	console.log(document.domain);
        ///                    document.cookie = keys[i] + &apos;=0;path=/;expires=&apos; + new Date(0).toUTCString();//清除当前域名下的,例如：m.kevis.com
        ///                    document.cookie = keys[i] + &apos;=0;path=/;domain=&apos; + document.domain + &apos;;expires=&apos; + new Date(0).toUTCSt [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string clearCookie {
            get {
                return ResourceManager.GetString("clearCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var url = &apos;%{url}%&apos;;
        /// var crsf = &apos;%{csrf}%&apos;;
        /// $.ajax({
        ///            url: url,
        ///            data:crsf,
        ///            type: &quot;POST&quot;,
        ///            xhrFields: {
        ///                withCredentials: true
        ///            },
        ///            crossDomain: true,
        ///            success: function (data) {
        ///                interaction.setResult(JSON.stringify(data));
        ///            }
        /// }); 的本地化字符串。
        /// </summary>
        public static string followjs {
            get {
                return ResourceManager.GetString("followjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ;function getCookie(name){var arr,reg=new RegExp(&quot;(^| )&quot;+name+&quot;=([^;]*)(;|$)&quot;);if(arr=document.cookie.match(reg))return unescape(arr[2]);else return null}interaction.setResult(getCookie(&apos;%{name}%&apos;));; 的本地化字符串。
        /// </summary>
        public static string getcookiejs {
            get {
                return ResourceManager.GetString("getcookiejs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function (e, t) {
        ///    var n, r, i = typeof t, o = e.location, a = e.document, s = a.documentElement, l = e.jQuery, u = e.$, c = {}, p = [], f = &quot;1.10.2&quot;, d = p.concat, h = p.push, g = p.slice, m = p.indexOf, y = c.toString, v = c.hasOwnProperty, b = f.trim, x = function (e, t) { return new x.fn.init(e, t, r) }, w = /[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source, T = /\S+/g, C = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g, N = /^(?:\s*(&lt;[\w\W]+&gt;)[^&gt;]*|#([\w-]*))$/, k = /^&lt;(\w+)\s*\/?&gt;(?:&lt;\/\1&gt;|)$/, E = /^[\],:{}\s] [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string jquery {
            get {
                return ResourceManager.GetString("jquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 token=&apos;&apos;;
        ///function login() {
        ///	var name = &quot;%{name}%&quot;;
        ///	var pwd = &quot;%{password}%&quot;;
        ///	var device_id = &quot;%{device_id}%&quot;;
        ///	var baseUrl = &quot;%{url}%&quot;;
        ///	var url = baseUrl + &quot;/webchat/api/v1/sessions&quot;;
        ///	var data = {
        ///	device_id:device_id,password: pwd,username: name};
        ///	var xhr = new XMLHttpRequest();
        ///	xhr.open(&quot;POST&quot;, url, true);
        ///	xhr.setRequestHeader(&quot;Content-Type&quot;, &quot;text/plain;charset=UTF-8&quot;);
        ///	xhr.onreadystatechange = function() {
        ///		if (xhr.readyState == 4 &amp;&amp; (xhr.status == 200 || xhr.status == 304)) {
        ///i [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string loginjs {
            get {
                return ResourceManager.GetString("loginjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function getCookie(name){
        ///	  var arr,reg=new RegExp(&quot;(^| )&quot;+name+&quot;=([^;]*)(;|$)&quot;);
        ///	  if(arr=document.cookie.match(reg))
        ///	          return unescape(arr[2]);
        ///	  else 
        ///	  	return null;
        ///	 }
        ///	 function logout(){ 
        ///                	
        ///                	var baseUrl = &quot;&quot;; 
        ///                	var id = getCookie(&quot;SPC_U&quot;); 
        ///                	if(null == id){
        ///                		id = getCookie(&quot;SPC_SC_UD&quot;); 
        ///                	}
        ///                	confirm(&quot;退出:&quot;+id); 
        ///                	var url = baseUrl + &quot;/webchat/api [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string logoutjs {
            get {
                return ResourceManager.GetString("logoutjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function order(){var baseUrl=&apos;%{url}%&apos;;window.location=baseUrl+&quot;/portal/sale&quot;}order(); 的本地化字符串。
        /// </summary>
        public static string orderjs {
            get {
                return ResourceManager.GetString("orderjs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap QQ图片20190515210139 {
            get {
                object obj = ResourceManager.GetObject("QQ图片20190515210139", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap QQ图片20190515210156 {
            get {
                object obj = ResourceManager.GetObject("QQ图片20190515210156", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap QQ图片20190515210204 {
            get {
                object obj = ResourceManager.GetObject("QQ图片20190515210204", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 var script=document.createElement(&quot;script&quot;);
        ///
        ///script.type=&quot;text/javascript&quot;;
        ///script.src=&quot;https://translate.google.cn/translate_a/element.js?cb=googleTranslateElementInit&quot;;
        ///
        ///document.getElementsByTagName(&apos;head&apos;)[0].appendChild(script); 
        ///
        ///
        ///script.onload=function(){
        /// googleTranslateElementInit();
        ///};//js加载完成执行方法
        ///var divObj=document.createElement(&quot;div&quot;); 
        /////divObj.setAttribute(&apos;id&apos;,&apos;topAlert&apos;); 
        ///divObj.innerHTML=&apos;&lt;div id=&quot;google_translate_element&quot; style=&quot;position:absolute;bottom:10px;right:10px;z-in [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string translate {
            get {
                return ResourceManager.GetString("translate", resourceCulture);
            }
        }
    }
}
